a="my name is joston//////\n////"
print(a.title())
print(a.istitle())
print(a.isalpha())
print(a.isalnum())
print(a.replace("joston","luvis"))
print(a.lower())
print(a.find("0"))
print(a.index("t"))
print(a.capitalize())
print(a.swapcase())
print(a.startswith(("i")))
print(a.endswith("n"))
print(a.rstrip("/"))
print(a.count("o"))
print(a.split("  "))
print(a.isprintable())