"a playbook is nothing but set of plays"
"s sterps"
"hosts: where we have to execute the module"
"tasks: which modules to execute"
===============================================================================================================================================
structure
===========================================================================================================
-  name: name of play
  host : host group name
  tasks:
   - name: name pf the task
     ModuleName: parameters1= val par2=val
  - name: give task 2 name
    ModuleName: parameter=val par2=val
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
- name: Debug module of Ansible
  hosts: my
  tasks:
    - name: Print a message on the controller
      debug: msg="hello"
  *********************************************************************************************************
ansible-playbook playbook.yml --syntax-check "to check correct or not"
interpreter_python = auto_silent
ansible-playbook playbook.yml
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
- name: execute a command
  hosts: my
  tasks:
    - name: execute a command on the worker nodes
      command: hostname -s
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  - name: execute a command
  hosts: my
  tasks:
    - name: execute a command on the worker nodes
      command: hostname -s
      register: command_output
  ****************************************************************************************************************************
- name: execute a command
  hosts: my
  tasks:
    - name: execute a command on the worker nodes
      command: hostname -s
      register: command_output
    - name: print
      debug: var=command_output
  ***************************************************************************************************************************
- name: apache2
  hosts: my
  tasks:
    - name: update
      command: apt update
    - name: install web ser
      package: name=apache2 state=present
  ***************************************************************************************************************
- name: apache2
  hosts: my
  become: true
  become_user: root
  tasks:
    - name: update
      command: apt update
    - name: install maven
      package: name=maven state=present
    - name: install git
      package: name=git state=present
    - name: install apache2
      package: name=apache2 state=present
      become: true
      become_user: root
*********************************************************************************************************
- name: deploy
  hosts: my
  become: true
  tasks:
    - name: install on package on server
      package: name=apache2 state=present
    - name: sevice to start
      service: name=apache2 state=started
    - name: Deploy
      copy: src=index.html dest=/var/www/html
    - name: sevice to start
      service: name=apache2 state=restarted
  ******************************************************************************************************
- name: deploy
  hosts: my
  become: true
  tasks:
    - name: install on package on server
      package: name=apache2 state=present
    - name: sevice to start
      service: name=apache2 state=started
    - name: Deploy
      copy: src=index.html dest=/var/www/html
      notify: sevice to start
  handlers:
    - name: sevice to start
      service: name=apache2 state=restarted
**********************************************************************************************************************************
- name: aaaa
  hosts: my
  become: true
  tasks:
    - name: update
      command: apt update
    - name: install java
      package: name=openjdk-8-jdk state=present
    - name: install maven
      package: name=maven state=present
    - name: git
      ansible.builtin.git:  repo=https://github.com/luvis-joston-j/Balenci.git dest=/home/jos/balenci
********************************************************************************************************************************************
- name: install nginx
  hosts: my
  become: true
  become_user: root
  vars:
    pk: nginx
    pp: apache2
    path: /var/www/html
  tasks:
    - name: uninstall {{pp}}
      package: name=apache2 state=absent
    - name: uninstall {{ pk }}
      package: name={{ pk }} state=absent
    - name: install {{ pk }}
      package: name={{ pk }} state=latest
    - name: start
      service: name={{pk}} state=started
    - name: Deploy
      copy: src=index.html dest={{path}}
      notify: restart
  handlers:
      - name: restart
        service: name={{pk}} state=restarted
  **************************************************************************************************************************************
  - name: tomcat install
  hosts: my
  become: true
  tasks:
    - name: update
      command: apt update
    - name: un
      package: name=nginx state=absent
    - name: jdk
      package: name=openjdk-17-jdk state=present
    - name: maven
      package: name=maven state=present
    - name: docker
      package: name=docker.io  state=present
    - name: docker sv
      service: name=docker state=started
    - name: docker pull
      command: docker pull luvisjostonj/lv
    - name: docker co
      command: docker run -d -p 1234:3000 luvisjostonj/lv
**********************************************************************************************************************************
- name: my play to do assignment 1
  hosts: my
  become: true
  vars:
  tasks:
   - name: install java
     package: name=openjdk-21-jdk state=absent
   - name: install java
     package: name=openjdk-17-jdk state=absent
   - name: install java
     package: name=openjdk-8-jdk state=absent
   - name: install maven
     package: name=maven state=present
  #- name: git clone
  #  ansible.builtin.git: repo=https://github.com/luvis-joston-j/Balenci.git dest=/home/jos/Ba
   - name: build
     command: mvn clean package -e chdir=/home/jos/Ba
   - name: install tomcat
     command: wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.97/bin/apache-tomcat-9.0.97.tar.gz
   - name: unzip
     command: tar -xvf apache-tomcat-9.0.97.tar.gz
******************************************************************************************************************************
- name: my play to do assignment 1
  hosts: my
  become: true
  vars:
    d_p: /home/jos/Balenci #destination path 
    tom_path: /usr/local/tomcat/webapps # tomcat server root path
  tasks:
   - name: update
     command: apt-get update
   - name: java
     package: name=openjdk-8-jdk state=present #java installation
   - name: maven
     package: name=maven state=present #mavne installation
   - name: git
     package: name=git state=present #git installation
   - name: git clone #cloning a web app repo
     ansible.builtin.git: repo=https://github.com/luvis-joston-j/Balenci.git dest={{d_p}}
   - name: mvn build # building an artifact
     command: mvn clean package chdir={{d_p}}
   - name: docker #im going to use docker because it would be more easier to build tomcat server to deploy my java web app
     package: name=docker.io state=present
   - name: docker service
     service: name=docker state=started
   - name: docker pull tomcat #pulling tomcat image cuz java based apps are hosted on tomcat server
     command: docker pull tomcat
   - name: docker container with port mapping and volume
     command: docker run -d -v {{d_p}}/target:{{tom_path}} -p 2245:8080 tomcat
  *********************************************************************************************************************************************
