"a playbook is nothing but set of plays"
"s sterps"
"hosts: where we have to execute the module"
"tasks: which modules to execute"
===============================================================================================================================================
structure
===========================================================================================================
-  name: name of play
  host : host group name
  tasks:
   - name: name pf the task
     ModuleName: parameters1= val par2=val
  - name: give task 2 name
    ModuleName: parameter=val par2=val
