print("git fetch origin")
print("git rebase origin/main")
print("git remote add origin URL")
print("git push origin main")
print("do not ctrate more than 6 branch")
print("do xanax till im dead")
print("")
