print("git fetch origin")
print("git rebase origin/main")
print("git remote add origin URL")
print("git push origin main")
print("do not ctrate more than 6 branch")
print("do xanax till im dead")
print("git branch -M main cuz the deafualt brach of github is main")
print("joston")
print("luvis")
print("https://www.jenkins.io/doc/tutorials/tutorial-for-installing-jenkins-on-AWS/")
